import type { Metadata } from "next";
import "./globals.css";
import { dela_gothic, ibm_plex_sans } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`w-full h-full flex  ${ibm_plex_sans.variable} ${dela_gothic.variable} font-ibm-plex-sans`}
    >
      <body className="w-full h-max flex justify-center items-start">
        {children}
      </body>
    </html>
  );
}
